import Link from "next/link";
import Crosshair from "@/components/Crosshair";
import SystemCard from "@/components/SystemCard";
import Rise from "@/components/Rise";
import { getSite, getSystems, getPlayground } from "@/lib/content";

export default async function Home() {
  const [site, systems, playground] = await Promise.all([
      getSite(),
          getSystems(),
              getPlayground(),
                ]);

                  return (
                      <>
                            <header className="hero">
                                    <div>
                                              <Rise mode="mount">
                                                          <div className="eyebrow"><Crosshair size={13} /> BOGDAN · WINNIPEG, MB</div>
                                                                    </Rise>
                                                                              <Rise mode="mount" delay={90}>
                                                                                          <h1>{site.headline}<br /><span className="thin">{site.subhead}</span></h1>
                                                                                                    </Rise>
                                                                                                              <Rise mode="mount" delay={200}>
                                                                                                                          <p className="lede">{site.lede}</p>
                                                                                                                                    </Rise>
                                                                                                                                              <Rise mode="mount" delay={260}>
                                                                                                                                                          <div className="hero-actions">
                                                                                                                                                                        <Link href="/systems" className="action primary">SEE THE SYSTEMS →</Link>
                                                                                                                                                                                      <Link href="/contact" className="action secondary">START A CONVERSATION</Link>
                                                                                                                                                                                                  </div>
                                                                                                                                                                                                            </Rise>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                            <div className="hero-side">
                                                                                                                                                                                                                                      <Rise mode="mount" delay={320} className="telemetry">
                                                                                                                                                                                                                                                  {site.telemetry.map(({ k, v }) => (
                                                                                                                                                                                                                                                                <div key={k}><span className="k">{k}</span> — {v}</div>
                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                      </Rise>
                                                                                                                                                                                                                                                                                                <Rise mode="mount" delay={390}>
                                                                                                                                                                                                                                                                                                            <p className="hero-note"><span>METHOD</span> MESSY PROCESS → CLEAR MODEL → WORKING SYSTEM</p>
                                                                                                                                                                                                                                                                                                                      </Rise>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                    </header>

                                                                                                                                                                                                                                                                                                                                          <section id="systems">
                                                                                                                                                                                                                                                                                                                                                  <Rise>
                                                                                                                                                                                                                                                                                                                                                            <div className="sec-head">
                                                                                                                                                                                                                                                                                                                                                                        <span className="xh"><Crosshair size={16} /></span>
                                                                                                                                                                                                                                                                                                                                                                                    <h2>Systems</h2>
                                                                                                                                                                                                                                                                                                                                                                                                <Link href="/systems" className="tag-link">VIEW ALL →</Link>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  </Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="sys-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                    {systems.map((s, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                <Rise key={s.slug} delay={i * 90}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <SystemCard s={s} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="method-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="sec-head">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="xh"><Crosshair size={16} /></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>How I work</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="tag">OPERATOR → BUILDER</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="method-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ["01", "Map the mess", "Find the handoff, decision, and data problem underneath the symptoms."],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ["02", "Make the model", "Define the records, relationships, ownership, and source of truth."],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ["03", "Build the workflow", "Turn the model into a process people can run without relying on memory."],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ["04", "Leave it stronger", "Document the rules, automate the repeatable parts, and make the system usable."],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ].map(([num, title, body]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Rise key={num} delay={Number(num) * 55}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <article className="method-step">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>{num}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3>{title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>{body}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <section id="playground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="sec-head">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="xh"><Crosshair size={16} /></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>Human mode</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/playground" className="tag-link">VIEW ALL →</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="play-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {playground.map((p, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Rise key={p.slug} delay={i * 90}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="tile">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="glyph">{p.glyph}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4>{p.title}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>{p.body}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Rise>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          