import Link from "next/link";
import FeedEmbed from "@/components/FeedEmbed";
import { getFeed, feedConfig } from "@/lib/feeds";
export const metadata = { title: "Feeds — БОГMODE", description: "Writing, videos, and things that catch my attention." };
function FeedList({ feed, provider, profile }) { return <>{feed.items.length ? <div className="feed-list">{feed.items.map(item => <article key={item.url}><a href={item.url} rel="noreferrer" target="_blank"><h3>{item.title} ↗</h3></a>{item.date && !Number.isNaN(Date.parse(item.date)) && <time dateTime={item.date}>{new Date(item.date).toLocaleDateString("en-CA",{year:"numeric",month:"short",day:"numeric",timeZone:"UTC"})}</time>}{provider === "YouTube" && item.videoId && <FeedEmbed provider="YouTube" videoId={item.videoId} />}</article>)}</div> : <p className="contact-note">{feed.state === "unconfigured" ? "This channel will appear here once connected." : feed.state === "empty" ? "No public posts are available yet." : "The feed is temporarily unavailable. You can still visit the original channel."}</p>}{profile && <a className="tag-link" href={profile} target="_blank" rel="noreferrer">OPEN {provider.toUpperCase()} →</a>}</>; }
export default async function FeedsPage() {
  const [medium,youtube] = await Promise.all([getFeed("medium"),getFeed("youtube")]);
  return <section className="feeds-page"><div className="sec-head"><h1 className="page-title">Feeds</h1><span className="tag">OUTSIDE THE BRIEF</span></div><p className="lede">Things I write, things I film, and things worth passing along. A little more of the person behind the work.</p><nav className="feed-jump" aria-label="Feed channels"><a href="#medium">Medium</a><a href="#instagram">Instagram</a><a href="#youtube">YouTube</a></nav><section id="medium" className="feed-section"><span className="case-label">WRITING</span><h2>On Medium</h2><FeedList feed={medium} provider="Medium" profile={feedConfig.mediumProfile} /></section><section id="instagram" className="feed-section"><span className="case-label">DAILY FINDS</span><h2>Instagram · @bogmoder</h2><p>Memes, moments, and things that catch my attention.</p><FeedEmbed provider="Instagram" /></section><section id="youtube" className="feed-section"><span className="case-label">IN MOTION</span><h2>On YouTube</h2><FeedList feed={youtube} provider="YouTube" profile={feedConfig.youtubeProfile} /></section><p className="contact-note">Social embeds stay off until you load them. Medium headlines are fetched by this site’s server. <Link href="/privacy">Privacy & cookies →</Link></p></section>;
}
